# Generated by Django 2.1.15 on 2022-03-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time_minutes',
        ),
    ]
