# Generated by Django 2.1.15 on 2022-03-29 12:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_article_time_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.article_image_file_path),
        ),
    ]
